import { Outfit, Playfair_Display } from "next/font/google";
import "./globals.css";

const outfit = Outfit({
  subsets: ["latin"],
  weights: [400, 700],
  variable: "--font-outfit",
});

const playfairDisplay = Playfair_Display({
  subsets: ["latin"],
  weights: [400, 700],
  variable: "--font-playfair-display",
});

export const metadata = {
  title: "AnakNusa",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${outfit.variable} ${playfairDisplay.variable}`}
    >
      <body className={"font-outfit"}>{children}</body>
    </html>
  );
}
